# - Try to find OpenVDB
# Once done this will definie
# OPENVDB_FOUND - System has OpenVDB
# OPENVDB_INCLUDE_DIRS - The OpenVDB include directories
# OPENVDB_DEFINITIONS - Compiler switches required for using OpenVDB

if (${OPENVDB_HOME})
MESSAGE("OPENVDB_HOME = " ${OPENVDB_HOME})
endif(${OPENVDB_HOME})
FIND_PATH(OPENVDB_INCLUDE_DIR NAMES openvdb/openvdb.h
	HINTS /Users/Kacey/projects/OpenVDB/include
)

FIND_LIBRARY(OPENVDB_LIBRARY NAMES openvdb
	HINTS /Users/Kacey/projects/OpenVDB/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENVDB DEFAULT_MSG OPENVDB_LIBRARY OPENVDB_INCLUDE_DIR)

SET (OPENVDB_COMPILE_FLAGS)

IF (OPENVDB_FOUND)
	SET(OPENVDB_LIBRARIES ${OPENVDB_LIBRARY})
	SET(OPENVDB_INCLUDE_DIRS ${OPENVDB_INCLUDE_DIR})
ELSE()
	SET(OPENVDB_LIBRARIES)
	SET(OPENVDB_INCLUDE_DIR)
ENDIF()

MARK_AS_ADVANCED(OPENVDB_INCLUDE_DIR OPENVDB_LIBRARY)
